version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "weekly"
